/**
 * ExecutiveBriefingView.jsx — NeuroPulse Final Phase
 * Premium AI-generated "Executive Intelligence Briefing" panel.
 */
import { useState, useEffect } from 'react';
import { motion } from 'framer-motion';
import axios from 'axios';
import { ShieldAlert, Zap, Loader2, AlertTriangle, TrendingUp, CheckCircle, FileText, Download } from 'lucide-react';

const API = import.meta.env.VITE_API_URL || 'http://127.0.0.1:5000';

export default function ExecutiveBriefingView() {
  const [report, setReport] = useState('');
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    fetchBriefing();
  }, []);

  const fetchBriefing = async () => {
    setLoading(true);
    try {
      const res = await axios.get(`${API}/executive_briefing`);
      if (res.data.report) {
        setReport(res.data.report);
      } else {
        setReport("Briefing unavailable. Telemetry streams paused.");
      }
    } catch (err) {
      setReport("ERROR: Unable to connect to Gemini SOC Analyst Engine.");
    } finally {
      setLoading(false);
    }
  };

  const handleExport = () => {
    const blob = new Blob([report], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `Executive_Briefing_${new Date().toISOString().slice(0,10)}.md`;
    a.click();
  };

  return (
    <div style={{ padding: '2rem', height: '100%', overflowY: 'auto', display: 'flex', justifyContent: 'center' }}>
      <div style={{ width: '100%', maxWidth: 900 }}>
        
        {/* Header */}
        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: '2rem' }}>
          <div>
            <h2 style={{ fontSize: '1.4rem', fontWeight: 800, color: 'var(--text-1)', margin: '0 0 8px', display: 'flex', alignItems: 'center', gap: 10 }}>
              <FileText size={24} color="#f43f5e" /> Executive Intelligence Briefing
            </h2>
            <p style={{ color: 'var(--text-2)', fontSize: '0.85rem', margin: 0 }}>
              Generated by Gemini 2.5 Flash • Bloomberg SOC AI Analyst
            </p>
          </div>
          <motion.button onClick={handleExport} whileHover={{ scale: 1.05 }} style={{ display: 'flex', alignItems: 'center', gap: 8, padding: '8px 16px', background: 'var(--bg-elevated)', border: '1px solid var(--border-dim)', borderRadius: 8, color: 'var(--text-1)', cursor: 'pointer', fontSize: '0.8rem', fontWeight: 600 }}>
            <Download size={14} /> Export PDF/MD
          </motion.button>
        </div>

        {/* Quick Indicators */}
        <div style={{ display: 'flex', gap: 16, marginBottom: '2rem' }}>
          <div style={{ flex: 1, background: 'rgba(239,68,68,0.1)', border: '1px solid rgba(239,68,68,0.3)', borderRadius: 12, padding: '1rem', display: 'flex', alignItems: 'center', gap: 16 }}>
            <ShieldAlert size={28} color="#ef4444" />
            <div>
              <div style={{ fontSize: '0.65rem', color: '#fca5a5', textTransform: 'uppercase', letterSpacing: '0.1em', fontWeight: 700 }}>Risk Level</div>
              <div style={{ fontSize: '1.2rem', fontWeight: 800, color: '#ef4444' }}>ELEVATED</div>
            </div>
          </div>
          <div style={{ flex: 1, background: 'rgba(139,92,246,0.1)', border: '1px solid rgba(139,92,246,0.3)', borderRadius: 12, padding: '1rem', display: 'flex', alignItems: 'center', gap: 16 }}>
            <TrendingUp size={28} color="#8b5cf6" />
            <div>
              <div style={{ fontSize: '0.65rem', color: '#c4b5fd', textTransform: 'uppercase', letterSpacing: '0.1em', fontWeight: 700 }}>Momentum</div>
              <div style={{ fontSize: '1.2rem', fontWeight: 800, color: '#a78bfa' }}>NEGATIVE DRIFT</div>
            </div>
          </div>
          <div style={{ flex: 1, background: 'rgba(16,185,129,0.1)', border: '1px solid rgba(16,185,129,0.3)', borderRadius: 12, padding: '1rem', display: 'flex', alignItems: 'center', gap: 16 }}>
            <CheckCircle size={28} color="#10b981" />
            <div>
              <div style={{ fontSize: '0.65rem', color: '#6ee7b7', textTransform: 'uppercase', letterSpacing: '0.1em', fontWeight: 700 }}>Model Consensus</div>
              <div style={{ fontSize: '1.2rem', fontWeight: 800, color: '#34d399' }}>ALIGNED</div>
            </div>
          </div>
        </div>

        {/* AI Briefing Content */}
        <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }}
          style={{ background: 'var(--bg-surface)', backdropFilter: 'blur(20px)', border: '1px solid rgba(244,63,94,0.3)', borderRadius: 16, padding: '2rem', boxShadow: '0 8px 32px rgba(244,63,94,0.05)', position: 'relative' }}>
          
          <div style={{ position: 'absolute', top: 20, right: 20, display: 'flex', alignItems: 'center', gap: 6, fontSize: '0.7rem', color: '#f43f5e', fontWeight: 700, letterSpacing: '0.05em' }}>
            <Zap size={14} /> LIVE AI FEED
          </div>

          {loading ? (
            <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', padding: '4rem 0', gap: 16, color: '#f43f5e' }}>
              <Loader2 size={32} style={{ animation: 'spin 1s linear infinite' }} />
              <div style={{ fontSize: '0.85rem', fontWeight: 600, letterSpacing: '0.1em' }}>GENERATING EXECUTIVE SUMMARY...</div>
            </div>
          ) : (
            <div style={{ color: 'var(--text-1)', lineHeight: 1.7, fontSize: '0.9rem', whiteSpace: 'pre-wrap' }}>
              {report}
            </div>
          )}
        </motion.div>
      </div>
    </div>
  );
}
